### PR TITLE
Small fixes 

### LINKED ISSUE #210: Expand by default "data series options"
Hidden area occupies similar size as expanded. Users do not expect to find there "Delete all" button

### LINKED ISSUE #211: Calculators looks bad on large screens
screenshot from 2019-02-08 22-06-39

24'' monitor, resolution 1920 x 1200

### PR DESCRIPTION
**Pull request by marwin1991**
Link to bundle.js stats in footer
Fix view of calculations fixes #211
Expand data series by default fixes #210

### CODE REVIEW

File: src/components/layouts/MainPage.js [hunk 1]
```diff
@@ -77,6 +77,7 @@ class MainPage extends React.Component {
                         <Row>{confData.footerText}</Row>
                         <Row>{"Deploy date: " + confData.deployDate + " from branch: "
                             + confData.deployBranch + " and commit number: " + confData.deployCommit}</Row>
+                        <Row><a href="report.html" target="_blank">{"See the bundle.js analyze"}</a></Row>
```
Comment (grzanka) [inline src/components/layouts/MainPage.js]: Is it possible to display such stats only on deployment to https://libamtrack.github.io/web_dev ?
For regular users it may be a bit misterious ?

Comment (marwin1991) [reply src/components/layouts/MainPage.js]: done

**Comment by grzanka** [comment]
Looks OK new, merge at will
